=== Rodez-IUT/dut-info2-filmprovider-FlorianPerezRodez/Part1-XML-DTD/resources/XML3/Librairie.dtd
<!ENTITY copyright "&#xA9;Librairie &amp; Internet 2020">
<!ENTITY % personne "(nom, prénom?)">
<!ENTITY % description "(#PCDATA | em | strong | img)*">
        <!ELEMENT librairie (entete, livre+)>
        <!ELEMENT entete %description;>
            <!ELEMENT texte (#PCDATA)>
            <!ELEMENT strong (#PCDATA)>
            <!ELEMENT em (#PCDATA)>
            <!ELEMENT img (#PCDATA)>
                <!ATTLIST img src CDATA #REQUIRED>
                <!ATTLIST img title CDATA #IMPLIED>
        <!ELEMENT livre (titre,(auteur+|collectif),description,prix)>
            <!ELEMENT titre (#PCDATA)>
            <!ELEMENT auteur %personne;>
                <!ELEMENT nom (#PCDATA)>
                <!ELEMENT prénom (#PCDATA)>
            <!ELEMENT collectif (direction,membres)>
                <!ELEMENT direction %personne;>
                <!ELEMENT membres (#PCDATA)>
            <!ELEMENT description %description;>
            <!ELEMENT prix (#PCDATA)>
                <!ATTLIST prix tva CDATA #FIXED "5.5">
                <!ATTLIST prix devise (euro|livre|dollar) "euro">
                <!ATTLIST prix type (HT|TTC) "HT">
            <!ATTLIST livre numISBN NMTOKEN #REQUIRED>

=== Rodez-IUT/dut-info2-filmprovider-FlorianPerezRodez/Part1-XML-DTD/resources/XML3/Librairie.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE librairie SYSTEM "Librairie.dtd">
<librairie>
    <entete></entete>
    <livre numISBN="978-2-2-11-05573-4">
        <titre> L'îles des Zertes </titre>
        <titre> L'il </titre>
        <auteur>
                <nom>Ponti</nom>
                <prénom>Claude</prénom>
        </auteur>
        <description>Qui est Jules ? C'est un Zerte. Il vit sur une île. Il a un ami, Diouc. Des ennemis, comme le Martabaff, qui tape sur tout ce qu'il trouve. Et une étrange passion pour une brique à qui il offre beaucoup de fleurs. Heureusement, il finira par rencontrer avec Roméotte le véritable amour...</description>
        <prix>15,30</prix>
    </livre>
</librairie>
